### ISSUE TITLE
Survey on topics to explore in 2019

### ISSUE THREAD

**Issue by bobaekang** [bobaekang/icjia-r-user-group#16]
## Summary
Please leave a comment to share ideas for topics you would like explore with the R User Group in 2019.

## Main
In the previous meeting in November, it was agreed that we should choose specific topics to focus on and explore in 2019 in order to make the User Group more relevant to all members and their projects.

This Issue is meant to serve as a forum to collect your ideas for and interests in various topics.  Some examples for such topics are:
* Automating report generation with R Markdown
* Bayesian statistics with Stan and RStan
* Creating a static website with R Markdown
* Creating presentation slides with R Markdown
* Data visualization
* Data wrangling for spatial data
* R interface to the MS Office Suite (Word, Excel, PowerPoint, etc.)
* R package development
* R project organization for productivity (file structure, script format, etc.)
* Shiny application development
* Statistical modeling and analysis
* Version-control for a research project with Git
    * This is not specifically about R but relevant re: programmatic research workflow
* Web scraping
* ... more

**Please leave a comment** to pick/suggest one topic or more that you'd like to focus on in 2019.

**Comment by lgleich3** [comment]
Here are some of the things I'd be interested in learning:
Data visualization
Creating presentation slides with R Markdown
Web scraping
Data wrangling for spatial data
Automating report generation with R Markdown
Shiny application development

**Comment by justinilla** [comment]
**Data wrangling in general.** Maybe we could cover a more versatile data wrangling (i.e. learning what packages and methods are good for different types of desired outcome files). We could then drill down and specialize in a few we think are most important for the work we do (i.e. mapping, visualization, statistical analyses, merging and aggregating.

**Creating a package, program and/or routine.** Maybe this could be focused on producing a flexible tool set for data checking/cleaning that we can all borrow from. We could organize it based on what someone might ultimately want to do with the data (e.g. analyze using text X).

**Data visualization.** For summarizing/cleaning/checking data, exploring data for patterns, and presenting results. Maybe we could do the last one by type of analysis? (regression, chi-square, t-test, factor analysis, etc.).

**Producing/Publishing interactive visuals.** Basic charts and graphs, nothing too fancy yet. Using Highcharts in R maybe or some other method.

I'd like to eventually have a handy, reliable, default toolbox that others around me use that I can pick from when I want to perform a specific task. Perhaps this would include **R project organization for productivity or version-control stuff.**

**Comment by mwpowers** [comment]
GGPlot would be my vote. I tend to search for plots that look like what I want to do and then modify the code. That has it's limits.

**Comment by bobaekang** [comment]
I'm reopening this issue since the January meeting has not happened yet and therefore the issue thread is still relevant 😄
